# Generated by Django 4.0.4 on 2022-05-20 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0005_alter_persona_fono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fono',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
